// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtEiLiYdt33uWQPDGFVM2JXLtpefiruiY',
    appId: '1:684135445993:web:89ebac3aa987ee4a58c778',
    messagingSenderId: '684135445993',
    projectId: 'localbasket-cf506',
    authDomain: 'localbasket-cf506.firebaseapp.com',
    storageBucket: 'localbasket-cf506.appspot.com',
    measurementId: 'G-NEKFYNQFV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSae0lRhOizefqAbt9TpkGbjxqbiFO2No',
    appId: '1:684135445993:android:301f65b47eaa630f58c778',
    messagingSenderId: '684135445993',
    projectId: 'localbasket-cf506',
    storageBucket: 'localbasket-cf506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC489L-QxQIf50URHhAPSOqpcr__sOwCjc',
    appId: '1:684135445993:ios:89c2623b8a81ecd558c778',
    messagingSenderId: '684135445993',
    projectId: 'localbasket-cf506',
    storageBucket: 'localbasket-cf506.appspot.com',
    iosBundleId: 'com.example.localbasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC489L-QxQIf50URHhAPSOqpcr__sOwCjc',
    appId: '1:684135445993:ios:89c2623b8a81ecd558c778',
    messagingSenderId: '684135445993',
    projectId: 'localbasket-cf506',
    storageBucket: 'localbasket-cf506.appspot.com',
    iosBundleId: 'com.example.localbasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtEiLiYdt33uWQPDGFVM2JXLtpefiruiY',
    appId: '1:684135445993:web:fc7a8f67d036acde58c778',
    messagingSenderId: '684135445993',
    projectId: 'localbasket-cf506',
    authDomain: 'localbasket-cf506.firebaseapp.com',
    storageBucket: 'localbasket-cf506.appspot.com',
    measurementId: 'G-FGLZ471706',
  );
}
